export const sources = {
  amdAm5: ['AMD Socket AM5 Chipset, AMD', 'https://www.amd.com/en/products/processors/chipsets/am5.html'],
  amdAm4: ['AMD Socket AM4 Chipsets, AMD', 'https://www.amd.com/en/products/processors/chipsets/am4.html'],
  intel1851: ['Information About Intel Core Ultra Boxed Desktop Processors (Series 2), Intel', 'https://www.intel.com/content/www/us/en/support/articles/000099656/processors.html'],
  intelF: ['Does My Computer with Intel Core Processor Number Ending with "F" Need a Discrete Graphics Card?, Intel', 'https://www.intel.com/content/www/us/en/support/articles/000058487/processors.html'],
  dellMemory: ['How to Install or Upgrade RAM or System Memory in a Dell Computer, Dell', 'https://www.dell.com/support/kbdoc/en-us/000129299/how-to-upgrade-memory-in-your-computer'],
  ddr5Notch: ['Is DDR5 backwards compatible with DDR4?, Corsair', 'https://www.corsair.com/explorer/diy-builder/memory/is-ddr5-backwards-compatible/'],
  dellM2: ['Differences Between M.2 Cards, M.2 Slots, Keys, Sizes and Types, Dell', 'https://www.dell.com/support/kbdoc/en-us/000144170/how-to-distinguish-the-differences-between-m-2-cards'],
  atxGuide: ['ATX Version 3 Multi Rail Desktop Platform Power Supply Design Guide rev 2.1a (aligns to ATX 3.1 and PCIe CEM 5.1), Intel', 'https://cdrdv2-public.intel.com/336521/336521_Rev2p1a.pdf'],
  psuSizing: ['How to calculate PSU wattage for your PC, XPG', 'https://www.xpg.com/us/knowledgehub/power-supply-unit/how-to-calculate-psu-wattage-for-your-pc/'],
  boardSizes: ['ATX vs MicroATX vs Mini-ITX: What\'s the Difference?, Corsair', 'https://www.corsair.com/us/en/explorer/diy-builder/cases/atx-vs-microatx-vs-mini-itx-whats-the-difference/'],
  intelBuild: ['How to Build a Gaming PC, Intel', 'https://www.intel.com/content/www/us/en/gaming/resources/how-to-build-a-gaming-pc.html'],
  crucialSpeeds: ['RAM Memory Speeds And Compatibility, Crucial', 'https://www.crucial.com/support/memory-speeds-compatability'],
  crucialInstall: ['How to Upgrade and Install RAM in a Desktop Computer, Crucial', 'https://www.crucial.com/support/articles-faq-memory/how-to-upgrade-desktop-memory'],
  gpuCaseFit: ['What is the best PC case for the RTX 4080 Super / 4090?, Corsair', 'https://www.corsair.com/us/en/explorer/diy-builder/cases/what-is-the-best-case-for-the-rtx-4080-super-4090/'],
  psuForms: ['ATX vs SFX vs SFX-L: Power Supply Form Factors and Sizes Explained, Corsair', 'https://www.corsair.com/us/en/explorer/diy-builder/power-supply-units/power-supply-form-factors-and-sizes-explained/'],
  coolerFit: ['Corsair 2000D Cooler compatibility, Corsair', 'https://www.corsair.com/us/en/explorer/diy-builder/cases/corsair-2000d-cooler-compatibility/'],
  intelRaid: ['Defining RAID Volumes for Intel Rapid Storage Technology, Intel', 'https://www.intel.com/content/www/us/en/support/articles/000005867/technologies.html'],
  intelRaidLevels: ['Supported Levels for Intel RAID Controllers, Intel', 'https://www.intel.com/content/www/us/en/support/articles/000008091/server-products/sasraid.html'],
  dellRaid: ['PowerEdge: What are the different RAID levels and their specifications, Dell', 'https://www.dell.com/support/kbdoc/en-us/000128635/dell-servers-what-are-the-raid-levels-and-their-specifications'],
  dellVirtualConsole: ['PowerEdge: How to Launch the Integrated Dell Remote Access Controller (iDRAC) Virtual Console, Dell', 'https://www.dell.com/support/kbdoc/en-ed/000179797/dell-poweredge-idrac-virtual-console'],
  intelTurbo: ['Intel Core Ultra 7 Processor 265KF Specifications, Intel', 'https://www.intel.com/content/www/us/en/products/sku/241062/intel-core-ultra-7-processor-265kf-30m-cache-up-to-5-50-ghz/specifications.html'],
  asusGpuPower: ['[Graphics card] Troubleshooting of power detection LED turns red or flashes, ASUS ROG', 'https://rog.asus.com/au/support/faq/1049767/'],
  kingstonSodimm: ['Memory Module Specifications KF556S40IB-32 (32 GB DDR5-5600 SO-DIMM), Kingston', 'https://www.kingston.com/datasheets/KF556S40IB-32.pdf'],
  kingstonPopulation: ['DDR4 and DDR5 Memory Population Rules based on Chipset and Processor Pairs, Kingston', 'https://www.kingston.com/en/memory/memory-population-rules'],
};

// Primer section `body`: a string, or an array of paragraph strings and tables
// (a table is an array of rows of cell strings; first row = header). SPEC addendum.
export const primer = {
  title: 'Build a PC that works the first time',
  sections: [
    { h: 'Platform first', body: 'The CPU socket must match the board socket: AM5 and LGA1851 boards use DDR5, older AM4 boards use DDR4. A board supports one DDR generation and one module shape: desktops take full-size DIMMs, laptops and many mini PCs take SO-DIMMs. Count modules against slots and total capacity against the board maximum.' },
    {
      h: 'Memory: shape, generation, slots, channels',
      body: [
        'Dell: desktops support DIMM modules and laptops support SO-DIMMs; a system board supports only one memory generation; every computer has a fixed number of memory slots and a maximum capacity (laptops often have two slots); and on some laptops the memory is built into the board and cannot be upgraded. Crucial: DDR5 will not work in DDR4 or DDR3 systems, and the system runs at the speed of the slowest module installed, so the best result comes from identical modules with the same specifications, installed in the slots the manual names for dual-channel operation. Before you buy, read the manual for slot count, maximum capacity and whether the memory is soldered.',
        [
          ['Check', 'Desktop', 'Laptop'],
          ['Module shape', 'DIMM', 'SO-DIMM (small outline)'],
          ['Generation', 'One per board (DDR4 or DDR5)', 'One per board (DDR4 or DDR5)'],
          ['Slots', '2 or more', 'Often 2; some laptops have memory built into the board'],
          ['Upgrade rule', 'Modules in the kit count against slots', 'Add a module that matches the installed one, or replace both'],
        ],
      ],
    },
    { h: 'Video path', body: 'The motherboard video ports only carry a picture when the CPU has integrated graphics. A CPU without graphics (an Intel model ending in F, or an AMD model without graphics) needs a dedicated graphics card, and the monitor plugs into the card. A home-built server without remote management usually needs a working local display for firmware and OS setup; a server with a management controller can use a remote console.' },
    {
      h: 'Fit in the case',
      body: [
        'Board sizes: ATX 305 x 244 mm, Micro-ATX 244 x 244 mm, Mini-ITX 170 x 170 mm. A case takes its own size and smaller, never larger. Mini-ITX boards have only 2 memory slots, 1 x16 slot and very few SATA ports. Check the case spec sheet for maximum graphics card length (a front radiator takes some of it), card thickness in slots, power supply size and CPU cooler height. Small cases leave little room above the CPU: Corsair gives its 2000D small case 90 mm of cooler clearance, so an air cooler for it must be lower than that.',
        [
          ['Power supply size', 'Width x height x length', 'Where it goes'],
          ['ATX', '150 x 86 x 140, 160 or 180 mm', 'Mid towers and most Micro-ATX cases'],
          ['SFX', '125 x 63.5 x 100 mm', 'Small form factor and Mini-ITX cases'],
          ['SFX-L', '125 x 63.5 x 130 mm', 'Small cases with room for 30 mm more length'],
        ],
      ],
    },
    {
      h: 'Storage',
      body: [
        'M.2 2280 means 22 mm wide and 80 mm long. The NVMe M.2 drives in this lab are M-keyed PCIe x4 drives. Other PCIe M.2 cards can use different keys; match key, size, and bus support to the board slot. The SATA M.2 drive in this lab is B+M keyed so it fits an M slot, but it only works in a slot that supports SATA, and many current boards have NVMe-only M.2 slots. Dell: M.2 drives on the PCIe bus are faster than SATA ones, and a SATA drive runs at SATA speed whatever its shape. A 2.5in or 3.5in SATA drive needs its own SATA port and a bay of its size. A faster PCIe drive works in a slower slot at the slot speed.',
        [
          ['Drive', 'Connects to', 'Needs'],
          ['NVMe M.2 2280 (PCIe 4.0 or 5.0)', 'M.2 slot with PCIe/NVMe', 'A free M.2 slot that lists NVMe or PCIe'],
          ['SATA M.2 2280 (B+M key)', 'M.2 slot with SATA', 'A free M.2 slot that lists SATA'],
          ['2.5in SATA SSD', 'SATA port + SATA power', 'One SATA port and one 2.5in bay'],
          ['3.5in SATA hard drive', 'SATA port + SATA power', 'One SATA port and one 3.5in bay'],
        ],
      ],
    },
    {
      h: 'Planning RAID for a file server',
      body: [
        'RAID combines drives into one volume. Intel: RAID 0 stripes for speed with no redundancy (one failed drive loses all data); RAID 1 mirrors two drives and keeps the space of one; RAID 5 needs at least 3 drives, keeps (number of drives minus 1) x the smallest drive, and survives one drive failure; RAID 10 uses four drives as a stripe of two mirrors and keeps the space of half of them; RAID 6 adds a second parity block so the array survives any two drive failures. Count the drives you want before buying the board and case: each needs a port and a bay. Minimum drive counts depend on the controller: Intel lists three drives for RAID 6 on its controllers, Dell lists four on its PowerEdge controllers. Check that the chosen board or controller supports the intended RAID level. RAID does not replace a separate backup.',
        [
          ['Level', 'Minimum drives', 'Survives', 'Usable space from 4 x 8 TB'],
          ['RAID 0', '2', 'No drive failure', '32 TB'],
          ['RAID 1', '2 (a mirrored pair)', 'One drive of the pair', '8 TB for one mirrored pair; two pairs are separate 8 TB volumes'],
          ['RAID 5', '3', 'One drive failure', '24 TB'],
          ['RAID 10', '4', 'One failure guaranteed; two if in different mirror pairs', '16 TB'],
          ['RAID 6', '3 or 4 depending on the controller (Intel 3, Dell PowerEdge 4)', 'Any two drive failures', '16 TB'],
        ],
      ],
    },
    { h: 'Graphics card power', body: 'The x16 slot gives up to 75 W and each 8-pin PCIe lead up to 150 W. A 12V-2x6 lead (PCIe CEM 5.1) uses sense pins to tell the card whether the power supply allows 150, 300, 450 or up to 600 W through it, and it replaces the older 12VHPWR. The ATX design guide recommends a 12V-2x6 connector on power supplies above 450 W; it does not require one. The ATX 3.1 units in this parts catalog list a native lead; check the rating on a real PSU. A card with a 12V-2x6 socket needs a native 12V-2x6 lead or its included adapter on enough separate 8-pin leads. Seat the plug fully.' },
    { h: 'Power supply size (this lab\'s rule)', body: [
        'Estimate = (CPU TDP + GPU board power + 75 W for board, memory, drives and fans) x 1.3, rounded up to the next common size (300, 350, 400, 450, 500, 550, 650, 750, 850, 1000, 1200 W and up). Example: 120 W CPU + 300 W card + 75 W = 495 W; x 1.3 = 644 W; the lab estimate is 650 W. XPG recommends keeping estimated draw under 80% of the rating and about 25% over the estimate for high-end cards; 1.3 sits just above both. This lab formula is a first-pass estimate, not a real PSU minimum. Check CPU maximum turbo power, GPU maker recommendations, drive count, PSU 12 V capacity, and transient-load support before selecting a real unit. Example: a 125 W Intel Core Ultra 7 265KF has a 250 W maximum turbo power, and XPG also suggests a supply 150 to 200 W above the total draw for sudden GPU spikes.',
        [
          ['Build', 'CPU + GPU + 75 W', 'x 1.3', 'Lab estimate'],
          ['Office PC, 65 W CPU, no card', '140 W', '182 W', '300 W'],
          ['Workstation, 125 W CPU, 300 W card', '500 W', '650 W', '650 W'],
          ['Gaming PC, 120 W CPU, 360 W card', '555 W', '722 W', '750 W'],
        ],
      ],
    },
    { h: 'Blank screen on a new build', body: 'Fans spin but the monitor says No signal: before blaming the monitor or the board, check the video path. Is the cable in the graphics card when there is one? Does the CPU have integrated graphics when the cable is in the motherboard port? Then check memory: a module of the wrong shape or generation will not seat, and a system with no working memory cannot finish its power-on self-test.' },
  ],
  src: ['amdAm5', 'amdAm4', 'intel1851', 'intelF', 'dellMemory', 'ddr5Notch', 'crucialSpeeds', 'crucialInstall', 'dellM2', 'atxGuide', 'psuSizing', 'boardSizes', 'psuForms', 'gpuCaseFit', 'coolerFit', 'intelRaid', 'intelRaidLevels', 'dellRaid', 'dellVirtualConsole', 'intelTurbo', 'kingstonPopulation', 'intelBuild'],
};

export const terms = {
  'integrated graphics': 'Graphics built into the CPU. The motherboard video ports only work when the installed CPU has it.',
  DIMM: 'Full-size desktop memory module.',
  'SO-DIMM': 'Small outline memory module used in laptops and many mini PCs. It does not fit desktop DIMM slots.',
  'dual-channel': 'Two memory channels used at once. Install matching modules in the slots the manual names for it.',
  TDP: 'The CPU rated thermal design power. This lab uses it as the CPU share of the power estimate.',
  'board power': 'The total power a graphics card is rated to draw. This lab uses it as the card share of the power estimate.',
  '12V-2x6': 'PCIe CEM 5.1 graphics power connector that can advertise 150, 300, 450, or up to 600 W through sense pins. It succeeds 12VHPWR.',
  'ATX 3.1': 'Desktop power supply design guide revision. A 12V-2x6 connector is recommended above 450 W, not guaranteed; check the PSU specifications and cable rating.',
  SFX: 'A small power supply size (125 x 63.5 x 100 mm) for small form factor and Mini-ITX cases.',
  'Mini-ITX': 'The smallest common motherboard size, 170 x 170 mm, with 2 memory slots and one x16 slot.',
  'M.2 2280': 'An M.2 card 22 mm wide and 80 mm long.',
  NVMe: 'A storage protocol over PCIe. This lab uses M-keyed M.2 NVMe SSDs; check the slot key, size and PCIe support.',
  'SATA M.2': 'An M.2 SSD that uses the SATA bus. It needs an M.2 slot that supports SATA and runs at SATA speed.',
  RAID: 'Several drives combined into one volume for speed, redundancy or both (levels 0, 1, 5, 6, 10).',
  NAS: 'Network attached storage: a small file server that shares its drives with the office over the network.',
};

const cases = [{
  id: 'build-01', title: 'Black screen at the front desk', level: 1,
  scenario: 'Ternfield Family Clinic ordered a front-desk PC for email and scheduling. The assembled PC powers on and the fans spin, but the monitor plugged into the motherboard HDMI port says "No signal". The memory kit on the parts cart has not been installed yet. Fix the parts list so the PC shows video and every part is compatible; the technician will plug the monitor into whichever video port the finished build uses.',
  examObjs: { 'aplus-1201': ['3.3', '3.5', '5.1'] }, objs: [], minutes: 6,
  picks: {
    cpu: 'cpu-am5-6c-n', board: 'board-am5-matx-basic', memory: ['ram-d5-so-32'], storage: ['ssd-nvme4-1t'],
    gpu: null, psu: 'psu-450-atx', case: 'case-matx', cooler: 'cooler-low-95',
  },
  goals: [
    {
      id: 'video', text: 'The PC has a working video output', check: { key: 'video', op: 'truthy' },
      why: 'A blank screen with "No signal" on a new build often means nothing is producing a picture. Motherboard video ports need a CPU with integrated graphics. A dedicated graphics card also gives a picture, but only on the card\'s own ports, so the monitor cable has to move from the motherboard HDMI port to the card.',
      expect: 'A CPU with integrated graphics drives the motherboard HDMI port. A dedicated graphics card also works if the monitor cable moves to the card.',
      hints: ['Read the CPU spec line. Where does the picture for the motherboard HDMI port come from?', 'This CPU has no integrated graphics and there is no graphics card. For an office PC, swap to the same-socket CPU that has graphics.', 'CPU slot: choose "AM5 6-core 65 W CPU with graphics".'],
      src: ['intelF', 'amdAm5'],
    },
    {
      id: 'memory', text: 'At least 16 GB of memory that fits this board', check: { all: [{ key: 'memory.totalGB', op: 'gte', value: 16 }, { not: { rule: 'memoryForm' } }, { not: { rule: 'memoryType' } }, { not: { rule: 'memorySlots' } }] },
      why: 'Memory must match the board on DDR generation and module shape. A laptop SO-DIMM is shorter than a desktop DIMM and will not seat in a desktop slot, even when both say DDR5.',
      expect: 'A DDR5 desktop DIMM kit of 16 GB or more, with no more modules than the board has slots (2).',
      hints: ['Compare the memory kit shape with the slots on the board.', 'The cart kit is SO-DIMM (laptop). This board needs DDR5 DIMMs, and it has only 2 slots.', 'Memory slot: choose "16 GB DDR5-5600 desktop kit (2 x 8 GB)".'],
      src: ['dellMemory', 'ddr5Notch'],
    },
    {
      id: 'compatible', text: 'Every part is installed and compatible', check: { all: [{ ok: true }, { complete: true }] },
      why: 'One wrong part stops the whole build. Re-check the full list after every swap: socket, memory, case fit, power and cooling.',
      expect: 'The compatibility panel shows no errors and every slot except the optional graphics card is filled.',
      hints: ['Look at the compatibility panel for any remaining errors.', 'Fix the video path and the memory; the other cart parts already fit.', 'Choose the AM5 CPU with graphics and the 16 GB DDR5 desktop kit; leave the rest as is.'],
      src: ['intelBuild'],
    },
  ],
  traps: [
    { id: 'no-video', check: { rule: 'noVideo' }, critical: true, message: 'No video output: this CPU has no integrated graphics and no graphics card is installed, so the motherboard HDMI port stays dark. The PC can power on and spin its fans with no picture at all.', why: 'Before blaming the monitor or the board, check that something in the build can produce a picture: integrated graphics in the CPU or a dedicated card.', src: ['intelF'] },
    { id: 'laptop-memory', check: { rule: 'memoryForm' }, message: 'SO-DIMM laptop memory does not fit desktop DIMM slots. Forcing it can damage the module or the slot.', why: 'Match the module shape (DIMM or SO-DIMM) as well as the DDR generation.', src: ['dellMemory'] },
    { id: 'wrong-generation', check: { rule: 'memoryType' }, message: 'DDR4 memory does not fit a DDR5 board. The notch is in a different place and the board supports only one generation.', why: 'Read the board memory type first, then buy that generation.', src: ['dellMemory', 'ddr5Notch'] },
  ],
  solution: [
    { do: { slot: 'cpu', part: 'cpu-am5-6c-g' }, explain: 'Swap to the AM5 CPU with integrated graphics. Same socket, same 65 W, and the motherboard HDMI port now has a picture to send. For an email and scheduling PC this is cheaper than adding a graphics card.' },
    { do: { slot: 'memory', part: 'ram-d5-16' }, explain: 'Replace the laptop SO-DIMM kit with a 16 GB DDR5 desktop DIMM kit: 2 modules for the 2 slots, DDR5 like the board.' },
  ],
  trapDemo: [
    { trap: 'no-video', steps: [] },
    { trap: 'laptop-memory', steps: [] },
    { trap: 'wrong-generation', steps: [{ do: { slot: 'memory', part: 'ram-d4-16' } }] },
  ],
  src: ['intelF', 'dellMemory', 'ddr5Notch', 'amdAm5', 'intelBuild'],
}, {
  id: 'build-02', title: 'Laptop memory upgrade to 32 GB', level: 1,
  scenario: 'Dana Okafor at Harbor Lane Design runs out of memory editing large layouts on her 14in laptop. The laptop has 2 DDR5 SO-DIMM slots: one holds a 16 GB DDR5-5600 SO-DIMM and the other is empty. Her manager ordered a "32 GB DDR5-6000 desktop kit" and left it on the bench next to the open laptop. Only the memory can change: get the laptop to 32 GB with parts that fit.',
  examObjs: { 'aplus-1201': ['3.3'] }, objs: [], minutes: 5,
  slots: ['memory'],
  picks: {
    cpu: 'cpu-laptop-bga', board: 'board-laptop', memory: ['ram-d5-so-16', 'ram-d5-32'], storage: ['ssd-nvme4-1t'],
    gpu: null, psu: null, case: null, cooler: null,
  },
  goals: [
    {
      id: 'shape', text: 'Every module is a DDR5 SO-DIMM that fits the laptop', check: { all: [{ key: 'memory.modules', op: 'gte', value: 1 }, { not: { rule: 'memoryForm' } }, { not: { rule: 'memoryType' } }] },
      why: 'Laptops take SO-DIMMs and desktops take full-size DIMMs, and a board supports only one DDR generation. "DDR5" on the box is not enough: the module shape has to match the slot too.',
      expect: 'Only DDR5 SO-DIMM modules are installed; the desktop DIMM kit goes back.',
      hints: ['Compare the shape of each module with the slots on this laptop board.', 'The kit the manager ordered is a desktop DIMM kit. The laptop needs DDR5 SO-DIMMs.', 'Memory slot: remove "32 GB DDR5-6000 desktop kit (2 x 16 GB)".'],
      src: ['dellMemory', 'ddr5Notch'],
    },
    {
      id: 'capacity', text: '32 GB total in no more than the 2 slots', check: { all: [{ key: 'memory.totalGB', op: 'gte', value: 32 }, { not: { rule: 'memorySlots' } }, { not: { rule: 'memoryCapacity' } }] },
      why: 'Count modules, not kits: each module occupies one slot. For this catalog, keep the installed 16 GB DDR5-5600 SO-DIMM and add a matching 16 GB module to reach 32 GB and populate both channels. A single 32 GB SO-DIMM listed in the laptop manual would also reach 32 GB, but in one channel; this catalog has none.',
      expect: 'With the parts in this catalog: two 16 GB DDR5 SO-DIMMs, either the installed one plus an identical module, or a 2 x 16 GB SO-DIMM kit in place of it.',
      hints: ['How many slots does this laptop have, and how many modules are on the list now?', 'Keep the 16 GB SO-DIMM already installed and put a second, identical 16 GB DDR5-5600 SO-DIMM in the empty slot.', 'Memory slot: add "16 GB DDR5-5600 laptop module (1 x 16 GB SO-DIMM)" so the list is two of them.'],
      src: ['dellMemory', 'crucialInstall', 'crucialSpeeds', 'kingstonSodimm'],
    },
    {
      id: 'compatible', text: 'The memory change leaves no compatibility errors', check: { all: [{ ok: true }, { complete: true }] },
      why: 'An upgrade is done when the whole system checks out, not when the new part is in. Re-check after every swap.',
      expect: 'The compatibility panel shows no errors with the memory installed.',
      hints: ['Look at the compatibility panel after your change.', 'The errors all come from the memory list: wrong module shape and too many modules.', 'Remove the desktop kit and add a second 16 GB DDR5-5600 SO-DIMM.'],
      src: ['dellMemory'],
    },
  ],
  traps: [
    { id: 'desktop-kit', check: { rule: 'memoryForm' }, message: 'A desktop DIMM does not fit a laptop SO-DIMM slot: it is longer and the slot cannot hold it. The kit cannot be installed, whatever its speed or capacity.', why: 'Match the module shape (DIMM or SO-DIMM) as well as the DDR generation. Laptop memory is listed as SO-DIMM.', src: ['dellMemory'] },
    { id: 'ddr4-sodimm', check: { rule: 'memoryType' }, message: 'DDR4 SO-DIMMs do not fit a DDR5 laptop. The key notch is in a different place, and pushing it in can break the module or the slot.', why: 'A board supports one DDR generation. Read the memory type in the laptop specifications before buying.', src: ['dellMemory', 'ddr5Notch', 'crucialSpeeds'] },
    { id: 'too-many', check: { rule: 'memorySlots' }, message: 'More modules than slots: a 2-slot laptop cannot hold the installed module plus a 2-module kit. One of them stays on the bench.', why: 'Count modules, not kits. With every slot full, upgrading means replacing modules, not adding them.', src: ['dellMemory'] },
  ],
  solution: [
    { do: { slot: 'memory', remove: 'ram-d5-32' }, explain: 'Take the desktop DIMM kit off the list. It is DDR5, but DIMMs are for desktops and will not fit the laptop SO-DIMM slots.' },
    { do: { slot: 'memory', add: 'ram-d5-so-16' }, explain: 'Add a second 16 GB DDR5-5600 SO-DIMM, identical to the one already installed. Two matching modules fill both slots, reach 32 GB and let the memory run in dual-channel mode.' },
  ],
  trapDemo: [
    { trap: 'desktop-kit', steps: [] },
    { trap: 'ddr4-sodimm', steps: [{ do: { slot: 'memory', parts: ['ram-d4-so-16'] } }] },
    { trap: 'too-many', steps: [{ do: { slot: 'memory', parts: ['ram-d5-so-16', 'ram-d5-so-32'] } }] },
  ],
  src: ['dellMemory', 'ddr5Notch', 'crucialSpeeds', 'crucialInstall', 'kingstonSodimm'],
}, {
  id: 'build-03', title: 'Gaming PC: power and fit for a big card', level: 2,
  scenario: 'Marcus Lee already bought a high-end 360 W graphics card (330 mm long, one 12V-2x6 socket, adapter for three 8-pin leads included) and wants a gaming PC built around it. The draft parts list from the shop reuses a Micro-ATX compact tower and a 550 W ATX power supply from a smaller build. The card stays; fix the rest so it fits and has enough power.',
  examObjs: { 'aplus-1201': ['3.5', '3.6'] }, objs: [], minutes: 10,
  slots: ['cpu', 'board', 'memory', 'storage', 'psu', 'case', 'cooler'],
  picks: {
    cpu: 'cpu-am5-8c-g', board: 'board-am5-matx', memory: ['ram-d5-32'], storage: ['ssd-nvme4-2t'],
    gpu: 'gpu-360', psu: 'psu-550-atx', case: 'case-matx', cooler: 'cooler-tower-180',
  },
  goals: [
    {
      id: 'card-fits', text: 'The graphics card fits in the case', check: { all: [{ key: 'case', op: 'truthy' }, { not: { rule: 'gpuFit' } }] },
      why: 'Every case lists a maximum graphics card length (and a front radiator takes some of it). Big cards are often longer than the photos suggest, so compare millimetres before buying.',
      expect: 'A case whose maximum GPU length is at least 330 mm and that takes a 3-slot card.',
      hints: ['Compare the card length with the case spec line.', 'The compact tower takes cards up to 320 mm; this card is 330 mm. Pick a case with more room that still takes a Micro-ATX board.', 'Case slot: choose "ATX mid tower" (400 mm card limit).'],
      src: ['gpuCaseFit', 'boardSizes'],
    },
    {
      id: 'psu-watts', text: 'The power supply meets the lab\'s wattage estimate', check: { all: [{ key: 'psu', op: 'truthy' }, { not: { rule: 'psuWattage' } }] },
      why: 'Size the power supply from the parts: CPU TDP + GPU board power + 75 W for the rest, times 1.3 for headroom, rounded up to a common size. A unit run near its limit runs hot and can shut down under load spikes.',
      expect: '120 W + 360 W + 75 W = 555 W; x 1.3 = 722 W; so a 750 W or larger power supply.',
      hints: ['Work out the estimate from the primer rule before choosing.', '555 W x 1.3 is about 722 W, so the 550 W unit is too small and so is 650 W. The next size in the catalog that clears it is 850 W.', 'Power supply slot: choose "850 W ATX 3.1 power supply".'],
      src: ['psuSizing', 'atxGuide'],
    },
    {
      id: 'card-power', text: 'The card\'s 12V-2x6 socket has a proper power connection', check: { all: [{ key: 'psu', op: 'truthy' }, { not: { rule: 'gpuPower' } }] },
      why: 'A 12V-2x6 card needs a native 12V-2x6 lead (the ATX 3.1 units in this parts catalog list a native lead; check the rating on a real PSU) or its included adapter on enough separate 8-pin leads, 150 W each. Missing or loose auxiliary power can prevent startup, trigger a warning, or cause unstable operation.',
      expect: 'A power supply with a native 12V-2x6 lead, such as the ATX 3.1 units in this catalog (or one with at least three separate 8-pin leads for the adapter).',
      hints: ['Count what the card needs and what the power supply offers.', 'The adapter needs three 8-pin leads and the 550 W unit has two. The ATX 3.1 units in this catalog list a native 12V-2x6 lead.', 'Power supply slot: choose "850 W ATX 3.1 power supply" (native 12V-2x6).'],
      src: ['atxGuide', 'asusGpuPower'],
    },
    {
      id: 'compatible', text: 'Every part is installed and compatible', check: { all: [{ ok: true }, { complete: true }] },
      why: 'After changing the case and power supply, re-check the rest: board size in the new case, cooler height, memory and storage.',
      expect: 'The compatibility panel shows no errors.',
      hints: ['Look at the compatibility panel after each swap.', 'Only the case and the power supply need to change; the Micro-ATX board fits an ATX mid tower.', 'Choose "ATX mid tower" and "850 W ATX 3.1 power supply"; keep the rest.'],
      src: ['intelBuild', 'boardSizes'],
    },
  ],
  traps: [
    { id: 'card-too-long', check: { rule: 'gpuFit' }, message: 'The 330 mm card is longer than the case allows. In real life the card hits the front of the case or the drive cage and the side panel will not close.', why: 'Check the case maximum GPU length (minus any front radiator) against the card length before buying either one.', src: ['gpuCaseFit'] },
    { id: 'psu-too-small', check: { rule: 'psuWattage' }, critical: true, message: 'The power supply is below the estimate for this CPU and card. Under a gaming load it can shut the PC off or run at its limit, hot and noisy. A 650 W unit sounds large, but this build needs 750 W or more.', why: 'Add CPU TDP, GPU board power and 75 W, multiply by 1.3 and round up to a common size. That lab estimate is a first pass; on a real build also check CPU maximum turbo power and the card maker recommendation.', src: ['psuSizing', 'atxGuide'] },
    { id: 'short-on-leads', check: { rule: 'gpuPower' }, message: 'Not enough 8-pin leads for this card\'s 12V-2x6 adapter: it needs three separate leads and this supply has two. Do not leave an adapter input empty; the card may refuse to start or report a power fault.', why: 'A 12V-2x6 card needs a native 12V-2x6 lead or one separate 8-pin lead for each adapter plug.', src: ['atxGuide', 'asusGpuPower'] },
  ],
  solution: [
    { do: { slot: 'case', part: 'case-atx-mid' }, explain: 'Move to the ATX mid tower: it takes cards up to 400 mm and 4 slots thick, and a mid tower takes the Micro-ATX board as well as ATX. The 155 mm tower cooler fits under its 170 mm limit.' },
    { do: { slot: 'psu', part: 'psu-850-atx31' }, explain: '120 W CPU + 360 W card + 75 W = 555 W; x 1.3 = 722 W, so at least 750 W. The 850 W ATX 3.1 unit clears that and this catalog unit lists a native 12V-2x6 lead for the card, so no adapter is needed.' },
  ],
  trapDemo: [
    { trap: 'card-too-long', steps: [] },
    { trap: 'psu-too-small', steps: [{ do: { slot: 'case', part: 'case-atx-mid' } }, { do: { slot: 'psu', part: 'psu-650-atx31' } }] },
    { trap: 'short-on-leads', steps: [] },
  ],
  src: ['gpuCaseFit', 'psuSizing', 'atxGuide', 'asusGpuPower', 'boardSizes', 'intelBuild'],
}, {
  id: 'build-04', title: 'Slim front-desk PC', level: 2,
  scenario: 'Juniper Hollow Dental bought slim Mini-ITX desktop cases so the reception PCs fit under the counter shelf. The PCs run the scheduling app and a browser, with the monitor on the motherboard DisplayPort. The draft parts list was copied from a Micro-ATX tower build. The case stays: make every part fit it.',
  examObjs: { 'aplus-1201': ['3.5', '3.6'] }, objs: [], minutes: 10,
  slots: ['cpu', 'board', 'memory', 'storage', 'gpu', 'psu', 'cooler'],
  picks: {
    cpu: 'cpu-1851-14c-g', board: 'board-1851-matx', memory: ['ram-d5-16'], storage: ['ssd-nvme4-500'],
    gpu: null, psu: 'psu-450-atx', case: 'case-itx-slim', cooler: 'cooler-low-95',
  },
  goals: [
    {
      id: 'itx-board', text: 'A Mini-ITX board that fits the slim case', check: { all: [{ key: 'board.formFactor', op: 'eq', value: 'Mini-ITX' }, { not: { rule: 'boardFit' } }, { not: { rule: 'socket' } }] },
      why: 'A case takes its own board size and smaller, never larger. Micro-ATX is 244 x 244 mm; this case only has room and mounting holes for Mini-ITX, 170 x 170 mm.',
      expect: 'An LGA1851 Mini-ITX board, so the CPU socket still matches.',
      hints: ['Compare the board size with the board sizes the case accepts.', 'The case takes Mini-ITX only. Keep the LGA1851 socket so the CPU still fits.', 'Board slot: choose "LGA1851 Mini-ITX board (B860-class)".'],
      src: ['boardSizes'],
    },
    {
      id: 'sfx-psu', weight: 2, text: 'An SFX power supply of 450 W or less that covers the load', check: { all: [{ key: 'psu.formFactor', op: 'eq', value: 'SFX' }, { key: 'psu.watts', op: 'lte', value: 450 }, { not: { rule: 'psuFit' } }, { not: { rule: 'psuWattage' } }] },
      why: 'ATX and SFX power supplies are different sizes: ATX is 150 x 86 mm across, SFX is 125 x 63.5 mm. Small form factor cases need SFX. Size it from the load: 65 W CPU + 75 W = 140 W; x 1.3 = 182 W, so 300 W is enough.',
      expect: 'A 300 W or 450 W SFX power supply.',
      hints: ['Check which power supply size the case takes.', 'The case takes SFX only, and this build needs about 182 W, so a small SFX unit is right; a 750 W unit is far more than needed.', 'Power supply slot: choose "300 W SFX power supply".'],
      src: ['psuForms', 'psuSizing'],
    },
    {
      id: 'cooler-fits', text: 'A CPU cooler that fits under the 58 mm clearance', check: { all: [{ key: 'cooler', op: 'truthy' }, { not: { rule: 'coolerHeight' } }, { not: { rule: 'coolerSocket' } }, { not: { rule: 'coolerTdp' } }] },
      why: 'In small cases the side or top panel limits cooler height. The cooler must also list the CPU socket and be rated for at least the CPU heat load.',
      expect: 'A low-profile cooler no taller than 58 mm that supports LGA1851 and is rated for 65 W or more.',
      hints: ['Compare the cooler height with the case clearance.', 'The 68 mm cooler is too tall for 58 mm. Pick a slimmer one that supports LGA1851 and 65 W.', 'Cooler slot: choose "Slim low-profile cooler, 47 mm, 65 W".'],
      src: ['coolerFit', 'intelBuild'],
    },
    {
      id: 'igpu', text: 'Video comes from the CPU integrated graphics', check: { all: [{ key: 'cpu.integratedGraphics', op: 'truthy' }, { key: 'video', op: 'truthy' }] },
      why: 'The monitor is on the motherboard port, which only works with a CPU that has integrated graphics. For office work it saves the cost, power and space of a card.',
      expect: 'A CPU with integrated graphics (this one already has it), monitor on the motherboard port.',
      hints: ['Where does the picture for the motherboard DisplayPort come from?', 'Keep a CPU with integrated graphics; an "F" model has none.', 'CPU slot: keep "LGA1851 14-core 65 W CPU with graphics".'],
      src: ['intelF'],
    },
    {
      id: 'compatible', weight: 2, text: 'Every part is installed and compatible', check: { all: [{ ok: true }, { complete: true }] },
      why: 'A small case leaves no slack: re-check board size, power supply size, cooler height and socket after every swap.',
      expect: 'The compatibility panel shows no errors.',
      hints: ['Look at the compatibility panel.', 'Three parts were chosen for a tower: the board, the power supply and the cooler.', 'Choose the LGA1851 Mini-ITX board, the 300 W SFX power supply and the 47 mm slim cooler.'],
      src: ['boardSizes', 'psuForms', 'coolerFit'],
    },
  ],
  traps: [
    { id: 'matx-board', check: { rule: 'boardFit' }, message: 'A Micro-ATX board does not fit a Mini-ITX case. The board is larger than the tray and its mounting holes do not line up.', why: 'Bigger cases take smaller boards, never the reverse. Read the board sizes the case supports.', src: ['boardSizes'] },
    { id: 'atx-psu', check: { rule: 'psuFit' }, message: 'An ATX power supply does not fit a case built for SFX. It is wider, taller and longer than the opening.', why: 'Small form factor cases usually take SFX. Check the power supply size the case lists, not only the wattage.', src: ['psuForms'] },
    { id: 'tall-cooler', check: { rule: 'coolerHeight' }, message: 'The cooler is taller than the case clearance, so the cover will not close or will press on the cooler.', why: 'Compare the cooler height with the case maximum CPU cooler height before buying. Small cases need low-profile coolers.', src: ['coolerFit'] },
    { id: 'f-cpu', check: { rule: 'noVideo' }, critical: true, message: 'An "F" CPU has no integrated graphics, and this slim PC has no graphics card, so the motherboard DisplayPort stays dark.', why: 'If the monitor uses motherboard ports, the CPU must have integrated graphics. An "F" model needs a dedicated card.', src: ['intelF'] },
  ],
  solution: [
    { do: { slot: 'board', part: 'board-1851-itx' }, explain: 'Swap to the LGA1851 Mini-ITX board: 170 x 170 mm fits the slim case, and the socket still matches the CPU. Its 2 memory slots take the 2-module 16 GB kit and its M.2 slot takes the NVMe drive.' },
    { do: { slot: 'psu', part: 'psu-300-sfx' }, explain: 'The case takes SFX power supplies only. 65 W CPU + 75 W = 140 W; x 1.3 = 182 W, so a 300 W SFX unit covers it.' },
    { do: { slot: 'cooler', part: 'cooler-slim-65' }, explain: 'The 47 mm slim cooler fits under the 58 mm clearance with margin, supports LGA1851 and is rated for the 65 W CPU.' },
  ],
  trapDemo: [
    { trap: 'matx-board', steps: [] },
    { trap: 'atx-psu', steps: [] },
    { trap: 'tall-cooler', steps: [] },
    { trap: 'f-cpu', steps: [{ do: { slot: 'cpu', part: 'cpu-1851-20c-f' } }] },
  ],
  src: ['boardSizes', 'psuForms', 'coolerFit', 'psuSizing', 'intelF', 'intelBuild'],
}, {
  id: 'build-05', title: 'Video-editing workstation', level: 3,
  scenario: 'Northgate Media needs a workstation for 4K video editing: at least 64 GB of memory, the projects on a fast NVMe SSD, an 8 TB hard drive for the archive, and the 300 W creator graphics card for effects and export. The draft list reuses a 32 GB kit, a 1 TB SATA M.2 SSD from the spares drawer and a 550 W power supply. The 20-core "F" CPU and the LGA1851 Micro-ATX board are already chosen; fix the list.',
  examObjs: { 'aplus-1201': ['3.3', '3.4', '3.5', '3.6'] }, objs: [], minutes: 14,
  slots: ['memory', 'storage', 'gpu', 'psu', 'case', 'cooler'],
  picks: {
    cpu: 'cpu-1851-20c-f', board: 'board-1851-matx', memory: ['ram-d5-32'], storage: ['ssd-m2sata-1t', 'hdd-8t-7200'],
    gpu: 'gpu-300', psu: 'psu-550-atx', case: 'case-matx', cooler: 'cooler-tower-180',
  },
  goals: [
    {
      id: 'ram-64', text: 'At least 64 GB of memory that fits the board', weight: 2, check: { all: [{ key: 'memory.totalGB', op: 'gte', value: 64 }, { not: { rule: 'memoryType' } }, { not: { rule: 'memoryForm' } }, { not: { rule: 'memorySlots' } }, { not: { rule: 'memoryCapacity' } }] },
      why: 'Editing high-resolution video keeps a lot in memory. Reach the target with DDR5 DIMMs, no more modules than slots and no more than the board maximum; one matched kit is the safest way.',
      expect: '64 GB or more of DDR5 desktop DIMMs in at most 4 modules, for example a 2 x 32 GB kit.',
      hints: ['Compare the installed total with the 64 GB target, then count the board slots.', 'Replace the 32 GB kit with a 64 GB DDR5 kit (2 x 32 GB), which leaves two slots free for later.', 'Memory slot: choose "64 GB DDR5-6000 desktop kit (2 x 32 GB)".'],
      src: ['dellMemory', 'crucialInstall'],
    },
    {
      id: 'nvme', text: 'Project NVMe SSD and 8 TB archive hard drive are both present', weight: 2, check: { all: [{ key: 'storage.nvme', op: 'gte', value: 1 }, { key: 'storage.hdd35', op: 'gte', value: 1 }, { not: { rule: 'm2Slot' } }, { not: { rule: 'sataPorts' } }, { not: { rule: 'driveBays' } }] },
      why: 'NVMe drives use PCIe lanes and are faster than SATA, and a SATA M.2 drive runs at SATA speed whatever its shape. An M.2 drive also needs a slot that carries its protocol: this board\'s M.2 slots are PCIe/NVMe only, so the SATA M.2 drive has nowhere to work. The ticket also asks for the 8 TB archive drive, which needs its SATA port and a 3.5in bay.',
      expect: 'An NVMe M.2 SSD for projects and the 8 TB SATA hard drive for the archive, each with a supported connection and bay.',
      hints: ['Read the M.2 slot details on the board and the drive type on each SSD.', 'The 1 TB SSD is SATA M.2 (B+M key) and this board has no SATA M.2 support. Use a PCIe 4.0 NVMe drive; a PCIe 5.0 drive would only run at 4.0 speed here.', 'Storage: remove "1 TB SATA M.2 2280 SSD (B+M key)" and add "2 TB PCIe 4.0 NVMe M.2 2280 SSD"; keep the 8 TB hard drive.'],
      src: ['dellM2', 'intelBuild'],
    },
    {
      id: 'card', text: 'The 300 W creator card stays, fits, and has power', weight: 2, check: { all: [{ key: 'gpu', op: 'eq', value: 'gpu-300' }, { key: 'video', op: 'truthy' }, { not: { rule: 'gpuFit' } }, { not: { rule: 'gpuPower' } }] },
      why: 'This CPU is an "F" model with no integrated graphics, so the card is both the video output and the export accelerator the ticket names. A smaller card would give a picture but not the effects and export performance asked for. It must fit the case and get all its power leads.',
      expect: 'Keep the 300 W creator card, which is 305 mm long and needs its 12V-2x6 connection.',
      hints: ['Check that the card stays in the build and fits the case.', 'Keep the creator card: the F CPU cannot drive a monitor without it. It is 305 mm and the case allows 320 mm.', 'Graphics slot: keep "Creator 300 W graphics card".'],
      src: ['intelF', 'gpuCaseFit', 'atxGuide', 'intelBuild'],
    },
    {
      id: 'psu', text: 'The power supply covers sustained CPU and GPU load', check: { all: [{ key: 'psu.watts', op: 'gte', value: 850 }, { not: { rule: 'psuWattage' } }] },
      why: 'Workstations run CPU and GPU at full load for long exports. The lab estimate (CPU TDP + GPU board power + 75 W, times 1.3, rounded up) gives 650 W, but it starts from CPU base power: a comparable 125 W Intel F CPU is rated for up to 250 W maximum turbo power, so 250 W + 300 W + 75 W is already 625 W before any margin, and XPG suggests a supply 150 to 200 W above the total draw.',
      expect: 'An 850 W or larger ATX supply with a native 12V-2x6 lead. For this workstation, check the CPU maximum turbo power and the PSU maker recommendation as well as the lab base-power estimate.',
      hints: ['Work out the estimate from the primer rule, then ask what the CPU draws at turbo during a long export.', 'The 650 W lab estimate uses CPU base power. Check maximum turbo power for a comparable 125 W Intel F CPU; choose the 850 W unit for this sustained-load workstation.', 'Power supply slot: choose "850 W ATX 3.1 power supply".'],
      src: ['psuSizing', 'intelTurbo', 'atxGuide'],
    },
    {
      id: 'compatible', text: 'Every part is installed and compatible', weight: 2, check: { all: [{ ok: true }, { complete: true }] },
      why: 'Three separate problems can hide in one list. Clear every error, then re-read the warnings.',
      expect: 'The compatibility panel shows no errors.',
      hints: ['Look at the compatibility panel.', 'Fix memory size, the M.2 drive and the power supply; the case, cooler and card already fit.', 'Choose the 64 GB DDR5 kit, the 2 TB PCIe 4.0 NVMe SSD (keep the hard drive) and the 850 W ATX 3.1 power supply.'],
      src: ['intelBuild'],
    },
  ],
  traps: [
    { id: 'sata-m2', check: { rule: 'm2Slot' }, message: 'The SATA M.2 drive fits the M key slot physically but this board\'s M.2 slots carry only PCIe/NVMe, so the drive will not work there. The PC then has no project drive.', why: 'An M.2 drive needs a slot with the right key, length and protocol. Read the board manual: many current boards have NVMe-only M.2 slots.', src: ['dellM2'] },
    { id: 'psu-too-small', check: { any: [{ rule: 'psuWattage' }, { key: 'psu.watts', op: 'lte', value: 750 }] }, critical: true, message: 'The power supply is too small for this workstation. Below 650 W it misses even the lab base-power estimate, and 650 W or 750 W leaves too little margin: a comparable 125 W F CPU can draw 250 W at maximum turbo, so CPU, card and the rest reach about 625 W before any headroom. Long exports load both at once, and an undersized unit can shut the PC down mid-render.', why: 'Start from the lab estimate, then check CPU maximum turbo power and the PSU maker guidance (XPG: 150 to 200 W above total draw) for sustained loads.', src: ['psuSizing', 'intelTurbo', 'atxGuide'] },
    { id: 'no-card', check: { any: [{ rule: 'noVideo' }, { all: [{ key: 'gpu', op: 'truthy' }, { key: 'gpu', op: 'ne', value: 'gpu-300' }] }] }, critical: true, message: 'The 300 W creator card is missing or swapped for a different card. Without any card this "F" CPU has no video output at all and the motherboard ports stay dark; with another card the PC is no longer the build the ticket specified for effects and export.', why: 'A CPU without integrated graphics always needs a dedicated card, and the monitor plugs into the card. When a ticket names a part, keep it.', src: ['intelF'] },
    { id: 'too-many-modules', check: { rule: 'memorySlots' }, message: 'Adding a 4-module kit to the 2 installed modules needs 6 slots; this board has 4. Two modules stay in the box.', why: 'Count modules, not kits. To grow past the free slots, replace modules with larger ones.', src: ['dellMemory'] },
  ],
  solution: [
    { do: { slot: 'memory', part: 'ram-d5-64' }, explain: 'Replace the 32 GB kit with the 64 GB DDR5 kit (2 x 32 GB). It meets the target with one matched pair, uses 2 of the 4 slots and is far below the 192 GB board maximum.' },
    { do: { slot: 'storage', parts: ['ssd-nvme4-2t', 'hdd-8t-7200'] }, explain: 'Swap the SATA M.2 SSD for a 2 TB PCIe 4.0 NVMe SSD: this board\'s M.2 slots are NVMe only and PCIe 4.0, so a PCIe 5.0 drive would only run at 4.0 speed. The 8 TB archive drive stays on a SATA port.' },
    { do: { slot: 'psu', part: 'psu-850-atx31' }, explain: 'Use the 850 W ATX 3.1 unit. The lab base-power calculation gives 650 W, but a comparable 125 W Intel F CPU can draw up to 250 W at turbo; sustained CPU and GPU work needs more margin. This catalog unit also lists a native 12V-2x6 lead.' },
  ],
  trapDemo: [
    { trap: 'sata-m2', steps: [] },
    { trap: 'psu-too-small', steps: [] },
    { trap: 'psu-too-small', steps: [{ do: { slot: 'psu', part: 'psu-650-atx31' } }] },
    { trap: 'no-card', steps: [{ do: { slot: 'gpu', part: null } }] },
    { trap: 'no-card', steps: [{ do: { slot: 'gpu', part: 'gpu-75' } }] },
    { trap: 'too-many-modules', steps: [{ do: { slot: 'memory', add: 'ram-d5-128' } }] },
  ],
  src: ['dellMemory', 'crucialInstall', 'dellM2', 'intelF', 'psuSizing', 'intelTurbo', 'atxGuide', 'gpuCaseFit', 'intelBuild'],
}, {
  id: 'build-06', title: 'Small-office file server', level: 3,
  scenario: 'Alder Street Accounting wants a file server for the office share with four 8 TB 3.5in hard drives (they plan RAID 5) and the OS on a small NVMe SSD. It will run without a monitor once set up, and no graphics card is planned: setup uses a monitor on the motherboard HDMI port. On the first test boot the fans spin but that monitor stays blank, and the drives do not all fit. Fix the build so it can be set up and holds all four drives.',
  examObjs: { 'aplus-1201': ['3.4', '3.5', '5.1'] }, objs: [], minutes: 14,
  picks: {
    cpu: 'cpu-am5-6c-n', board: 'board-am5-itx', memory: ['ram-d5-16'],
    storage: ['ssd-nvme4-500', 'hdd-8t-5400', 'hdd-8t-5400', 'hdd-8t-5400', 'hdd-8t-5400'],
    gpu: null, psu: 'psu-450-atx', case: 'case-matx', cooler: 'cooler-low-95',
  },
  goals: [
    {
      id: 'ports', text: 'All four hard drives have a SATA port', check: { all: [{ key: 'storage.hdd35', op: 'gte', value: 4 }, { not: { rule: 'sataPorts' } }] },
      why: 'Each 3.5in drive needs its own SATA data port. Mini-ITX boards have very few SATA ports, so a four-drive server needs a board with at least four.',
      expect: 'A board with 4 or more SATA ports and all four 8 TB hard drives still on the list.',
      hints: ['Count the hard drives and the SATA ports on the board.', 'The Mini-ITX board has 2 SATA ports for 4 drives. An AM5 Micro-ATX board has 4.', 'Board slot: choose "AM5 Micro-ATX board (B850-class)".'],
      src: ['boardSizes'],
    },
    {
      id: 'bays', text: 'The case has a 3.5in bay for every hard drive', check: { all: [{ key: 'case.bays35', op: 'gte', value: 4 }, { not: { rule: 'driveBays' } }] },
      why: 'Every drive needs a bay of its size as well as a port. A compact tower often has only one 3.5in bay.',
      expect: 'A case with at least four 3.5in bays that also takes the board and power supply.',
      hints: ['Compare the number of 3.5in drives with the 3.5in bays in the case.', 'The compact tower has one 3.5in bay. The Micro-ATX NAS case has four hot-swap bays.', 'Case slot: choose "Micro-ATX NAS case (4 hot-swap bays)".'],
      src: ['boardSizes'],
    },
    {
      id: 'video', text: 'The server has a video output for setup', check: { all: [{ key: 'cpu.integratedGraphics', op: 'truthy' }, { key: 'video', op: 'truthy' }] },
      why: 'This home-built server has no remote console specified. It needs working local video for setup; motherboard HDMI requires integrated graphics in the CPU. A blank screen with spinning fans points to the video path first.',
      expect: 'A CPU with integrated graphics drives the motherboard HDMI port during setup.',
      hints: ['The symptom is a blank screen with fans spinning. Where does the motherboard HDMI picture come from?', 'This CPU has no integrated graphics. Use the same-socket CPU that has graphics.', 'CPU slot: choose "AM5 6-core 65 W CPU with graphics".'],
      src: ['intelF', 'amdAm5', 'dellVirtualConsole'],
    },
    {
      id: 'compatible', text: 'Every part is installed and compatible, with the NVMe OS drive', check: { all: [{ ok: true }, { complete: true }, { key: 'storage.nvme', op: 'gte', value: 1 }] },
      why: 'Changing the board and case moves other limits: check the board size against the new case, the power supply size, the cooler height and the M.2 slot for the OS drive. The ticket puts the OS on its own NVMe SSD, so it stays on the list.',
      expect: 'No compatibility errors, four connected hard drives, and a supported NVMe SSD for the OS.',
      hints: ['Look at the compatibility panel after each swap.', 'Three changes: a CPU with graphics, a board with 4 SATA ports, a case with 4 drive bays.', 'Choose the AM5 CPU with graphics, the AM5 Micro-ATX board (B850-class) and the Micro-ATX NAS case.'],
      src: ['intelBuild', 'boardSizes'],
    },
  ],
  traps: [
    { id: 'no-video', check: { any: [{ rule: 'noVideo' }, { all: [{ key: 'gpu', op: 'truthy' }, { key: 'cpu.integratedGraphics', op: 'falsy' }] }] }, critical: true, message: 'No picture on the motherboard HDMI port: this CPU has no integrated graphics. With no card nothing produces video; with a card added, the picture goes to the card\'s ports while the setup monitor stays on the dark motherboard port. Either way you cannot reach the firmware or install the OS. This is the blank screen from the first test boot.', why: 'For this build, the setup monitor uses the motherboard HDMI port, so use a CPU with integrated graphics. On another build, a card works if the monitor cable moves to that card.', src: ['intelF', 'dellVirtualConsole'] },
    { id: 'short-on-ports', check: { rule: 'sataPorts' }, message: 'Only 2 SATA ports for 4 hard drives: two drives are not connected, and the RAID 5 array cannot be built.', why: 'Count SATA ports before choosing a small board. Mini-ITX boards usually have very few.', src: ['boardSizes'] },
    { id: 'short-on-bays', check: { rule: 'driveBays' }, message: 'The case has fewer 3.5in bays than drives, so some drives have nowhere to mount. A port alone is not enough.', why: 'Every drive needs a bay of its size; match the case to the drive count.', src: ['boardSizes'] },
    { id: 'atx-in-nas-case', check: { rule: 'boardFit' }, message: 'An ATX board does not fit the Micro-ATX NAS case. It has more ports, but it is 305 mm long and the case only takes Micro-ATX and Mini-ITX.', why: 'Pick the board and case together: the case lists the board sizes it accepts.', src: ['boardSizes'] },
  ],
  solution: [
    { do: { slot: 'cpu', part: 'cpu-am5-6c-g' }, explain: 'Swap to the AM5 6-core CPU with integrated graphics: same socket and 65 W, and the motherboard HDMI port now works for setup. No graphics card is needed after that.' },
    { do: { slot: 'board', part: 'board-am5-matx' }, explain: 'The AM5 Micro-ATX board has 4 SATA ports, one per hard drive, plus M.2 slots for the NVMe OS drive. Its 4 DIMM slots take the 16 GB kit.' },
    { do: { slot: 'case', part: 'case-matx-nas' }, explain: 'The Micro-ATX NAS case has four 3.5in hot-swap bays, takes the Micro-ATX board and an ATX power supply, and its 130 mm cooler limit clears the 68 mm cooler. Four 8 TB drives provide about 24 TB usable and tolerate one drive failure if the selected board, CPU, and RAID implementation support RAID 5. Verify that support in the board manual, configure the array, and keep a separate backup.' },
  ],
  trapDemo: [
    { trap: 'no-video', steps: [] },
    { trap: 'no-video', steps: [{ do: { slot: 'gpu', part: 'gpu-75' } }] },
    { trap: 'short-on-ports', steps: [] },
    { trap: 'short-on-bays', steps: [] },
    { trap: 'atx-in-nas-case', steps: [{ do: { slot: 'case', part: 'case-matx-nas' } }, { do: { slot: 'board', part: 'board-am5-atx' } }] },
  ],
  src: ['boardSizes', 'intelF', 'amdAm5', 'intelRaid', 'dellRaid', 'dellVirtualConsole', 'intelBuild'],
}];

export default cases;
