function deepFreeze(value) {
  if (!value || typeof value !== 'object' || Object.isFrozen(value)) return value;
  Object.keys(value).forEach((key) => deepFreeze(value[key]));
  return Object.freeze(value);
}

const question = (q, choices, answer, why) => ({ q, choices, answer, why });
const card = (text, extra) => Object.assign({ text }, extra || {});
const step = (text, extra) => Object.assign({ text }, extra || {});
const option = (win, text) => ({ win, text });
const spot = (text, answer) => ({ text, answer });

const guided = 'guided';
const standard = 'standard';

export const LESSONS = [
  {
    id: 'g1', track: guided, number: 1, title: 'Meet Your Computer', minutes: '~20',
    newIdea: 'the parts of the computer and the Start button',
    warmup: [
      question('What do you use to move the arrow on the screen?', ['mouse', 'keyboard', 'speaker'], 0, null),
      question('What does a computer screen show you?', ['pictures, words, and apps', 'nothing', 'only the time'], 0, null),
      question("You see a message on the screen you don't understand. What do you do?", ['ask a grown-up', 'click everything', 'turn it off'], 0, null),
    ],
    learn: [
      card('A computer has parts you touch: the **screen**, the **keyboard**, and the **mouse** (or a touchpad on a laptop).'),
      card('The little arrow that moves with the mouse is the **pointer**.'),
      card("The big picture behind everything is the **desktop**. It's home base."),
      card('The long bar along the bottom is the **taskbar**.'),
      card('The button with the Windows logo ⊞ is **Start**. It opens your apps.', { win: { '11': 'Start is usually in the **middle** of the taskbar.', '10': 'Start is in the **bottom-left corner**.' } }),
      card('Your keyboard has a **Windows key** with the same logo. Press it and Start opens.'),
      card("🛑 Something new pops up and you're not sure what it is? **Stop and get a grown-up.** You are not in trouble."),
    ],
    mission: [
      step('Point to the screen, the keyboard, and the mouse. Say each name out loud.'),
      step('Find the taskbar at the bottom of the screen.'), step('Find the Start button ⊞ on the taskbar.'),
      step('Click Start once. A menu opens.'), step('Click Start again to close it. (Pressing **Esc** also closes it.)'),
      step("Find the Windows key ⊞ on your keyboard. It's near the bottom-left. Press it: Start opens. Press it again: Start closes."),
      step("Hover (don't click) over 2 icons on the taskbar. A little name pops up. Say the names."),
      step('click Start → Settings (the gear ⚙️) → System → **About**. Look for **Windows specifications**, then **Edition**. Does it say Windows 10 or Windows 11? Close Settings with the X.', { grownup: true, kind: 'windowsCheck' }),
    ],
    typingWords: ['mouse', 'screen', 'start', 'click', 'home'],
    quiz: [
      question('What is the long bar along the bottom of the screen called?', ['📏 the ruler', '🧱 the taskbar', '🚪 the exit'], 1, 'The taskbar holds Start and the icons for your apps.'),
      question('Which button opens your apps?', ['⊞ Start', '🔊 the speaker', '🕐 the clock'], 0, 'Start is the doorway to every app on the computer.'),
      question('What happens when you press the Windows key ⊞?', ['The Start menu opens', 'The computer turns off', 'The screen goes dark'], 0, 'The Windows key is a keyboard shortcut for Start.'),
      question('What is the little arrow that moves when you move the mouse?', ['the pointer', 'the taskbar', 'the desktop'], 0, 'The pointer shows where your mouse is on the screen.'),
      question("A box pops up that you've never seen before. What do you do?", ['Click every button to see what happens', 'Stop and get a grown-up', 'Pull out the power cord'], 1, "Stopping and asking is what smart computer users do. You're never in trouble for asking."),
    ],
    passScore: 4,
    parentChecks: ['Points to and names the screen, keyboard, and mouse', 'Opens Start by clicking, then closes it', 'Opens and closes Start with the Windows key', 'Tells you whether the computer is Windows 10 or 11 (you checked Settings together)'],
    chest: [question('Which key opens Start?', ['Windows key ⊞', 'Space bar', 'Enter'], 0, null), question('Where does the taskbar live?', ['along the bottom of the screen', 'inside the mouse', 'on the keyboard'], 0, null)],
    item: 'start-blade', practice: 'Open Start 3 times (click, Windows key, click) and hover to find the names of 3 taskbar icons.',
    parentWatch: 'Hunting for Start at first is normal. What matters is whether he stops for the pop-up question instead of clicking.', after: null,
  },
  {
    id: 'g2', track: guided, number: 2, title: 'Open, Switch, Close', minutes: '~20-25', newIdea: 'apps live in windows, and you switch with the taskbar',
    warmup: [question('Which key opens Start?', ['Windows key', 'Space', 'Backspace'], 0, null), question('Where is the taskbar?', ['along the bottom', 'top', 'inside Start'], 0, null), question("Something pops up and you don't know what it is. You…", ['stop and get a grown-up', 'click it', 'close the computer'], 0, null)],
    learn: [
      card('An **app** is a program that does a job. **File Explorer** shows your files. **Notepad** lets you type. **Edge** shows websites (CodeQuest is open in Edge right now).'), card('Each open app lives in its own **window**.'), card('Apps that are open show an icon on the taskbar with a little line under it.'), card("**Click an app's taskbar icon to switch to it.**"),
      card('The top-right corner of every window has 3 buttons:', { list: ['**_ Minimize:** hides the window down on the taskbar.', '**□ Maximize:** makes the window fill the screen.', '**X Close:** closes the app.'] }), card('Closing a window does **not** turn off the computer.'), card("⚠️ Don't click X on the CodeQuest window. If you do by accident, open Edge again. CodeQuest remembers your step."),
    ],
    mission: [step('Open File Explorer: click the yellow folder icon on the taskbar. (No yellow folder? Hold the Windows key ⊞ and tap **E**.)'), step("Switch back to CodeQuest: click the Edge icon on the taskbar. You're back here!"), step('Switch to File Explorer again with its taskbar icon. Go back and forth 2 more times.'), step('In File Explorer, click **_** (minimize). The window hides. Find it on the taskbar and click to bring it back.'), step('Click **□** (maximize). The window fills the screen. Click the same button again to make it smaller.'), step('Open Notepad: click Start, type **notepad**, press **Enter**.'), step('Now 3 apps are open. Use the taskbar to visit each one: File Explorer → Notepad → CodeQuest.'), step("Close Notepad with its **X**. If it asks about saving, click **Don't save** (we didn't type anything we need. When it's real work, you'll click Save)."), step('Close File Explorer with its **X**. (Leave CodeQuest open!)')],
    typingWords: ['open', 'close', 'app', 'window', 'switch'],
    quiz: [question("How do you switch to an app that's already open?", ['Click its icon on the taskbar', 'Turn the computer off and on', 'Open it 5 more times'], 0, 'The taskbar keeps a button for every open app.'), question('What does the X in the top-right corner of a window do?', ['Closes that window', 'Deletes the computer', 'Makes the window bigger'], 0, 'X closes the app, and only that app.'), question('True or false: closing a window turns off the computer.', ['True', 'False'], 1, 'The computer stays on. Only that window closes.'), question('You clicked **_** (minimize). Where did the window go?', ["It's hiding on the taskbar", 'It got deleted', 'It moved to another computer'], 0, 'Minimize tucks a window away. Click its taskbar icon to bring it back.'), question('Which app shows your files and folders?', ['File Explorer', 'Notepad', 'Calculator'], 0, 'File Explorer is the map of everything saved on the computer.')],
    passScore: 4, parentChecks: ['Opens File Explorer by himself', 'Opens Notepad from Start by typing its name', 'Switches between 3 windows using the taskbar', 'Minimizes a window and brings it back', 'Closes Notepad and File Explorer with X, and leaves CodeQuest open'],
    chest: [question('Which button hides a window without closing it?', ['_ minimize', 'X close', '□ maximize'], 0, null), question('Where do you click to switch to an open app?', ['its icon on the taskbar', 'the desktop picture', 'the power button'], 0, null)], item: 'taskbar-boots', practice: 'Open Calculator and Notepad, switch between them 5 times with the taskbar, then close both.', parentWatch: "If he closes CodeQuest by accident, reopening Edge should drop him back on the same step. Tell me if it doesn't, because that's a bug.", after: null,
  },
  {
    id: 'g3', track: guided, number: 3, title: 'Folders Are Containers', minutes: '~20-25', newIdea: 'files vs folders, and making a folder',
    warmup: [question('How do you switch to an open app?', ['click its taskbar icon', 'restart', 'press Space'], 0, null), question('What does X do?', ['closes that window', 'turns off the computer', 'makes it bigger'], 0, null), question('Where does a minimized window go?', ['the taskbar', 'the trash', 'nowhere'], 0, null)],
    learn: [card('A **file** is one thing: a picture, a story, a song.'), card("A **folder** is a container that holds files. It's like a backpack that holds your stuff."), card('Folders look like little yellow folders.'), card('**Documents** is a folder made for your work.'), card("Inside Documents there's a folder with **your name** on it. That's your space. Your brother has his own. **Only open your own folder.**"), card('Good names help you find things later. **Rocks** is a much better name than **New folder**.'), card("New folders start empty. That's normal.")],
    mission: [step('Open File Explorer (Windows key ⊞ + **E**).'), step('On the left side, click **Documents**. (Can\'t see it? Click **This PC** on the left, then double-click **Documents**.)'), step('Double-click **[your folder]**, the one with your name.'), step('Make a new folder in here, using ONE of these:', { options: [option('11', 'click **+ New** at the top-left → **Folder**'), option('10', 'click **New folder** at the top (on the Home tab)'), option('both', 'right-click an empty white space → **New** → **Folder**')] }), step('A folder appears, and its name **New folder** is highlighted in blue. Type: **Rocks**'), step('Check the spelling. Fix mistakes with **Backspace**. Then press **Enter**.'), step("Double-click **Rocks** to open it. It's empty. New containers always start empty."), step('Click the **Back arrow ←** at the top-left to go back to [your folder].'), step('Oops, is your folder still called "New folder"? Get a grown-up. You\'ll learn how to rename it next lesson.', { grownup: true })],
    typingWords: ['folder', 'file', 'rocks', 'save', 'find'],
    quiz: [question('A folder is like a…', ['🎒 backpack that holds things', '🖼️ picture', '🎮 game'], 0, 'Folders are containers. They hold files and even other folders.'), question('Which one is a file?', ['A photo of your dog', 'The Documents folder', 'The taskbar'], 0, 'A file is one thing, like a photo. Documents is a folder, a container.'), question('Which folder name is best?', ['"New folder"', '"Rocks"', '"asdfgh"'], 1, "A clear name tells you what's inside without opening it."), question('Before pressing Enter on a new name, you should…', ['Check the spelling', 'Close the window', 'Press Enter 10 times'], 0, 'A quick check now saves hunting for a misspelled folder later.'), question("You open your brand-new folder and it's empty. What happened?", ["Nothing's wrong. New folders start empty", "It's broken", 'You deleted everything'], 0, 'A new container is empty until you put something in it.')],
    passScore: 4, parentChecks: ['Opens Documents, then his own folder, in File Explorer', 'Makes a folder named **Rocks**, spelled right, inside his own folder', 'Opens Rocks and uses the Back arrow to return'], chest: [question('What holds files?', ['a folder', 'the pointer', 'the taskbar'], 0, null), question('Which key fixes a typo?', ['Backspace', 'Esc', 'Windows key'], 0, null)], item: 'folder-backpack', practice: 'In [your folder], make two folders: **Dinosaurs** and **Space**.', parentWatch: null, after: null,
  },
  {
    id: 'g4', track: guided, number: 4, title: 'Find It and Keep It Tidy', minutes: '~25', newIdea: 'folders inside folders, renaming, and search',
    warmup: [question('A folder is a…', ['container', 'picture', 'app'], 0, null), question("Where's the folder made for your work?", ['Documents', 'taskbar', 'Start'], 0, null), question('Which key fixes a typo?', ['Backspace', 'Enter', 'Space'], 0, null)],
    learn: [card('Folders can go **inside** folders, like a small box inside a big box.'), card("**Rename** means giving something a new name. What's inside stays safe."), card('Lost? Click the **Back arrow ←**, or click **Documents** on the left and open your folder again.'), card('The **search box** at the top-right of File Explorer finds things by name.'), card('🛑 We are **not deleting** anything. Deleting is grown-up-only for now.')],
    mission: [step('Open File Explorer → **Documents** → double-click **[your folder]**. Find your **Rocks** folder.'), step('Double-click **Rocks** to go inside.'), step('Make a new folder in here (same ways as last time). Name it: **Rock1** and press Enter.'), step("That name doesn't tell us much. Let's rename it. Right-click **Rock1**, then:", { options: [option('10', 'click **Rename**'), option('11', 'click the **Rename** icon near the top of the menu (hover over the icons to see their names)'), option('both', 'click the folder once, then press **F2** (on some laptops: hold **Fn** and press F2)')] }), step('Type **Shiny Rocks** and press **Enter**.'), step('Click **Back ←** to return to [your folder]. Double-click **Rocks** again. **Shiny Rocks** is inside.'), step('Go back to [your folder]. Click the **search box** at the top-right, type **shiny**, and wait a moment. Double-click **Shiny Rocks** in the results.'), step('Close File Explorer.')],
    typingWords: ['rename', 'back', 'search', 'shiny', 'rocks'], quiz: [question('Renaming a folder…', ['Gives it a new name. The stuff inside stays', 'Deletes the stuff inside', 'Makes a copy'], 0, 'Rename only changes the label on the outside.'), question('Can a folder go inside another folder?', ['Yes', 'No', 'Only on weekends'], 0, 'Folders can hold other folders, like boxes inside boxes.'), question("You're lost in File Explorer. What's the best move?", ['Click Back ←, or click Documents and open your folder', 'Click random buttons', 'Close all your folders forever'], 0, 'Back and Documents always get you somewhere you know.'), question('Which name will be easier to find later?', ['"Rock1"', '"Shiny Rocks"', '"New folder (2)"'], 1, "Names that describe what's inside are easy to search for."), question('Where do you type to find a folder by its name?', ['The search box in File Explorer', 'The clock', 'The X button'], 0, 'Search looks through folders for you.')], passScore: 4,
    parentChecks: ['Goes into Rocks inside his own folder', 'Makes a new folder inside Rocks', 'Renames it to **Shiny Rocks** (right-click Rename or F2)', 'Finds Shiny Rocks using the search box', 'Uses Back to return to his own folder'], chest: [question('Rename changes the…', ['name', 'stuff inside', 'color'], 0, null), question('Lost in File Explorer? Click…', ['Back ←', 'the power button', 'X on everything'], 0, null)], item: 'rename-rune', practice: 'Inside Rocks, make **Rock2**, rename it **Smooth Rocks**, then find it with search.', parentWatch: 'On Windows 11 the right-click menu uses small icons, and F2 is often easier. If F2 does nothing on a laptop, try Fn + F2.', after: null,
  },
  {
    id: 'g5', track: guided, number: 5, title: 'Keyboard Keys and the STOP Rule', minutes: '~25', newIdea: 'special keys, and staying safe online (safety is the main one)',
    warmup: [question('Rename changes…', ['the name', "what's inside", 'nothing'], 0, null), question('Where do you search for a folder?', ['search box in File Explorer', 'the clock', 'Start button only'], 0, null), question('Can folders go inside folders?', ['yes', 'no'], 0, null)],
    learn: [card('Special keys:', { list: ['**Space bar** (the long one) puts a gap between words', '**Enter** starts a new line', '**Backspace** erases the letter to the left', '**Shift**: hold it for a CAPITAL letter', '**Arrow keys** ← → move the blinking line (the cursor)'] }), card('A **browser** is the app for websites. Ours is **Edge**.'), card('Some things online are **private**: your full name, home address, school, phone number, passwords, and photos of you.'), card("**The STOP rule: Stop. Don't click. Tell a grown-up.**"), card('Use the STOP rule when:', { list: ['a website asks for private stuff or your age', 'a pop-up says **"You won!"** or **"Your computer has a virus!"**', 'something wants you to **download** or **install**', "someone you don't know sends you a message", 'anything scary, rude, or weird shows up'] }), card('You are **never in trouble** for telling.')],
    mission: [step('Open Notepad (Start → type **notepad** → Enter).'), step('Type: **I stop and ask.** (Hold **Shift** and tap **i** for the capital I.)'), step('Press **Enter**. Type: **Rocks are cool!!!**'), step('Press **Backspace** 2 times to erase two of the "!" marks.'), step('Press **←** a few times to move the blinking cursor left, then **→** to move it back.'), step("Close Notepad. If it asks, click **Don't save** (this was just practice. Real work gets saved)."), step('**Spot It** (inside CodeQuest, pretend screens, nothing real): for each card, choose **OK** or **STOP**:', { kind: 'spotIt', cards: [spot('"YOU WON A FREE TABLET! Click here!"', 'stop'), spot('"Type your home address to get free game coins"', 'stop'), spot('The animal-facts page your grown-up picked for you', 'ok'), spot('"Download this to make your game faster"', 'stop'), spot('A message from "CoolGamer99": "what school do u go to?"', 'stop')], pass: 4 }), step("open a new tab in Edge with the **+** next to your tabs. Your grown-up picks a kids' website. Find one fun fact. Close **just that tab** with the small X on the tab.", { grownup: true })],
    typingWords: ['space', 'enter', 'shift', 'stop', 'ask'], quiz: [question('Which key puts a space between words?', ['Space bar', 'Enter', 'Shift'], 0, "It's the longest key on the keyboard, made for gaps between words."), question('Which key erases the letter just to the left of the blinking cursor?', ['Backspace', 'Space bar', 'Windows key'], 0, 'Backspace steps back and erases.'), question('A website asks for your home address. You…', ["Stop, don't click, tell a grown-up", 'Type it in fast', 'Make up an address'], 0, 'Your address is private. A grown-up decides if a site is OK.'), question('A pop-up says "Your computer has a virus! Click here to fix it!" You…', ['Stop and tell a grown-up', 'Click to fix it', 'Download the fixer'], 0, 'Scary pop-ups are a common trick. Real fixes come from your grown-up.'), question("Someone online you don't know asks what school you go to. You…", ["Don't answer, and tell a grown-up", 'Tell them', 'Ask about their school'], 0, 'Your school is private info, even if they seem friendly.')], passScore: 4,
    parentChecks: ['Types two short sentences in Notepad, using Shift for a capital and Enter for a new line', 'Fixes a mistake with Backspace', 'Gets at least 4 of 5 Spot It cards right (the app shows you his answers)', 'Says the STOP rule to you in his own words', 'Opens and closes a single tab with you'], chest: [question('The STOP rule is…', ["Stop. Don't click. Tell a grown-up.", 'Click, then tell', 'Keep it a secret'], 0, null), question('Hold which key for a capital letter?', ['Shift', 'Space', 'Backspace'], 0, null)], item: 'stop-sign-shield', practice: 'Type 3 sentences about a favorite animal (capitals, Enter, fix one mistake), then a new shuffled round of Spot It cards.', parentWatch: null, after: ['find his way around the Windows desktop', 'open, switch, minimize, and close apps', 'make, rename, and find folders', 'type short sentences and fix mistakes', 'use the STOP rule when something online looks wrong'],
  },
  {
    id: 's1', track: standard, number: 1, title: 'Windows Map + Alt+Tab', minutes: '~30-35', newIdea: 'the whole desktop map, switching with the keyboard, snapping windows',
    warmup: [question('Which app shows your files?', ['File Explorer', 'Calculator', 'Edge'], 0, null), question("What does X in a window's corner do?", ['closes it', 'saves it', 'hides it'], 0, null), question("A settings page you don't know opens. You…", ['leave it and ask a grown-up', 'change things', 'turn off Wi-Fi'], 0, null)],
    learn: [card('The map: **desktop** (home base) · **taskbar** (bottom bar) · **Start** ⊞ (all apps) · **search** (next to Start) · **notification area** (bottom-right: clock, sound, Wi-Fi).'), card('Windows 11 puts Start in the middle of the taskbar by default. Windows 10 puts it bottom-left.'), card('Window buttons: **_** minimize · **□** maximize · **X** close.'), card('**Alt + Tab:** hold **Alt**, tap **Tab** to step through your open windows, let go to jump in.'), card('**Windows key + D:** show the desktop. Press it again to bring your windows back.'), card('**Windows key + ← or →:** snap a window to half the screen. Great for CodeQuest on one side and your work on the other.'), card("Finishing up the right way: close your apps, then **Start → Power ⏻ → Shut down** (or whatever your family's rule is). Holding the power button is for emergencies only, and it's grown-up-only."), card('🛑 **Settings are grown-up territory** unless a lesson says otherwise.')],
    mission: [step('Find each part: taskbar, Start, search, and the clock in the notification area.'), step('Start → Settings ⚙️ → System → **About** → Windows specifications → **Edition**. Windows 10 or 11? Close Settings.', { grownup: true, kind: 'windowsCheck' }), step('Open 3 apps: File Explorer (**Windows key + E**), Notepad (Start → type **notepad** → Enter), and Calculator (Start → type **calculator** → Enter).'), step('Alt+Tab: hold **Alt**, tap **Tab** once, let go. You jumped to the last app. Now hold Alt and tap Tab twice. Visit all 3 apps using only Alt+Tab.'), step('Snap: click Notepad, press **Windows key + ←**. Click File Explorer, press **Windows key + →**. Side by side! (If little previews of your other windows show up, click one or press **Esc**.)'), step('Press **Windows key + D**: desktop. Press it again: your windows are back.'), step("Close Notepad (**Don't save** if asked, since that was practice text), Calculator, and File Explorer. Leave CodeQuest open.")],
    typingWords: ['alt', 'tab', 'desktop', 'snap', 'window', 'taskbar'], quiz: [question('What does Alt+Tab do?', ['Switches between open windows', 'Closes all apps', 'Opens Settings'], 0, "Alt+Tab is the fastest way to jump between what's open."), question('Where are the clock and the Wi-Fi icon?', ['Bottom-right, in the notification area', 'Inside Start', 'Inside File Explorer'], 0, 'The notification area sits at the right end of the taskbar.'), question('What does Windows key + D do?', ['Shows the desktop', 'Deletes a file', 'Opens Downloads'], 0, 'D stands for Desktop. Press it again to get your windows back.'), question('Where do you check whether a computer runs Windows 10 or 11?', ['Settings → System → About', 'Calculator', 'The Recycle Bin'], 0, 'About lists the Windows edition and version.'), question("A settings page you don't know opens up. What's the best move?", ['Leave it and ask a grown-up', 'Change things to see what happens', 'Turn off the Wi-Fi'], 0, 'Settings can change how the whole computer works for everyone.'), question("What's the right everyday way to turn off the computer?", ['Start → Power → Shut down', 'Hold the power button', 'Unplug it'], 0, 'Shut down lets Windows close things safely. Holding the button is for emergencies.')], passScore: 5,
    parentChecks: ['Found the Windows version with you', 'Opens File Explorer, Notepad, and Calculator without help', 'Reaches each app using only Alt+Tab', 'Snaps two windows side by side with Windows key + arrows', 'Shows the desktop with Windows key + D and brings the windows back'], chest: [question('Hold ___ and tap Tab to switch windows.', ['Alt', 'Ctrl', 'Shift'], 0, null), question('Windows key + ← does what?', ['snaps the window to the left half', 'closes it', 'shuts down'], 0, null), question('Is holding the power button the normal way to turn off?', ['No, emergencies only', 'Yes, always'], 0, null)], item: 'switch-sword', practice: 'Open 4 apps, reach each one with Alt+Tab, snap two of them side by side.', parentWatch: null, after: null,
  },
  {
    id: 's2', track: standard, number: 2, title: 'Files, Folders, Save and Find', minutes: '~35', newIdea: 'Save As (where + name), good file names, 3 ways to find a file',
    warmup: [question('Alt+Tab does…', ['switches windows', 'closes', 'saves'], 0, null), question('Windows key + D…', ['shows the desktop', 'deletes', 'downloads'], 0, null), question('Settings are…', ['grown-up territory', 'fun to explore', 'broken'], 0, null)],
    learn: [card('A **file** is one piece of work. A **folder** holds files, and folders can hold folders.'), card('**Documents** is where work lives. Inside it, **[your folder]** (with your name) is your space. Your brother has his own. **Only open your own folder.**'), card('The first time you save, **Save As** asks you two things: **where** (which folder) and **what name**.'), card('After that, **Ctrl + S** saves your changes to the same file.'), card('Name files so Future You can find them: **Favorite Animal Facts** beats **Document1**.'), card("You might see an ending like **.txt** after a file name. It's the **file extension**, and it tells Windows what kind of file it is. Don't change it."), card('Three ways to find a file: open its folder in File Explorer · the **File Explorer search box** · **Start search**.'), card('File Explorer can also show **Recent files**, if that\'s turned on: on the **Home** page in Windows 11, or in **Quick access** in Windows 10.')],
    mission: [step('File Explorer → **Documents** → double-click **[your folder]**. Make a folder named **My Projects**:', { options: [option('11', '**+ New** → **Folder**'), option('10', '**New folder** (Home tab)'), option('both', '**Ctrl + Shift + N**')] }), step('Open Notepad. Type 3 sentences about your favorite animal.'), step('Save it: **File → Save as**. In the window that opens, click **Documents** on the left, double-click **[your folder]**, then double-click **My Projects**. In **File name**, type **Favorite Animal Facts**. Click **Save**.'), step('Look at the top of Notepad. It shows your file\'s name now instead of "Untitled."'), step('Close Notepad.'), step('**Find it, way 1:** File Explorer → Documents → [your folder] → My Projects → double-click the file. It opens. Close it.'), step('**Find it, way 2:** File Explorer → Documents → [your folder] → click the search box → type **animal**. Open it from the results. Close it.'), step('**Find it, way 3:** Click Start and type **favorite animal**. Click your file in the results. (If it doesn\'t show up yet, that\'s OK. Way 1 always works.)'), step('Close everything except CodeQuest.')],
    typingWords: ['save', 'folder', 'project', 'find', 'name', 'file'], quiz: [question("What's the difference between a file and a folder?", ['A file is one piece of work. A folder holds files', "They're the same", 'A folder is a picture'], 0, 'Folders organize files the way drawers organize stuff.'), question('Which name will be easier to find next month?', ['"Document1"', '"Favorite Animal Facts"', '"aaaa"'], 1, 'Search works on names, so descriptive names are easy to find.'), question('The first time you save, Save As asks you for two things. What are they?', ['Where to put it, and what to name it', 'Color and size', 'Your password'], 0, 'Picking the folder and the name is what makes a file findable.'), question("You just saved a new file. What's a smart habit?", ['Check the name at the top, or find it in its folder', 'Assume it worked', 'Save it 20 more times'], 0, 'A two-second check proves the file is where you think it is.'), question('Where should your projects go?', ['A folder inside your own folder in Documents', 'Anywhere at all', 'The Recycle Bin'], 0, 'Keeping work in your own folder means you (and your grown-up) always know where to look.'), question('Your file shows as "Favorite Animal Facts.txt". What is ".txt"?', ['The extension, which says what kind of file it is. Leave it alone', 'A typo to delete', 'A secret code'], 0, 'Changing the extension can stop the file from opening correctly.')], passScore: 5,
    parentChecks: ['**My Projects** exists inside his own folder in Documents', '**Favorite Animal Facts** is saved inside My Projects (right place, right name)', 'Closes it and reopens it from File Explorer', 'Finds it with search (the File Explorer search box or Start)'], chest: [question("Which shortcut saves changes to a file that's already saved?", ['Ctrl + S', 'Alt + Tab', 'Windows key + D'], 0, null), question('Save As asks where and…', ['what name', 'what color', 'how big'], 0, null), question('Best place for your projects?', ['a folder inside your own folder', 'the desktop picture', 'Recycle Bin'], 0, null)], item: 'save-stone', practice: 'Write and save **Space Facts** into My Projects, close it, then find it with search.', parentWatch: null, after: null,
  },
  {
    id: 's3', track: standard, number: 3, title: 'Copy, Move, Rename + Ctrl+Z', minutes: '~35-40', newIdea: 'copy vs move, rename, undo',
    warmup: [question('Save As asks for…', ['where and what name', 'your password', 'a color'], 0, null), question('Where do projects go?', ['a folder inside your own folder', 'anywhere'], 0, null), question('".txt" is…', ['the file extension', 'a typo'], 0, null)],
    learn: [card('**Copy** makes a twin. The original stays where it was.'), card('**Move** picks it up and puts it somewhere else. The old spot is empty now.'), card('**Copy + Paste = copy.** **Cut + Paste = move.**'), card('The right-click menu: Windows 10 shows words (Cut, Copy, Paste, Rename). Windows 11 shows **small icons** for these near the top of the menu. Hover to see their names. **Show more options** opens the longer, older menu.'), card('**Rename:** right-click → Rename, or click the file once and press **F2**.'), card('**Ctrl + Z = undo.** Moved something to the wrong place or typed a bad name? Press Ctrl+Z right away.'), card("Before you paste, **check you're in the right folder** (look at the address bar at the top)."), card("🛑 Deleting sends things to the Recycle Bin, and we're not deleting today. If you ever delete something by accident, press **Ctrl + Z** right away, then tell a grown-up.")],
    mission: [step('File Explorer → Documents → [your folder] → **My Projects**. Make two folders: **Animals** and **Space**.'), step('**Move:** right-click **Favorite Animal Facts** → **Cut**. Double-click **Animals**. Right-click an empty space → **Paste**. Click **Back ←**. The file is gone from My Projects, because it moved into Animals.'), step("**Copy:** go into **Animals**. Right-click the file → **Copy**. Go Back, open **Space**, right-click an empty space → **Paste**. Now there's one in each folder."), step('**Rename the copy** in Space: click it once, press **F2** (or right-click → Rename). Type **Space Animal Facts**, press Enter. (If you see **.txt** at the end, leave it there.)'), step('**Undo, test 1:** rename that same file to **oops**, then press **Ctrl + Z**. The old name comes back!'), step('**Undo, test 2:** right-click **Space Animal Facts** → Cut, go into **Animals** → Paste. Now press **Ctrl + Z**. It jumps back into Space.'), step('Check: **Animals** has Favorite Animal Facts. **Space** has Space Animal Facts.')],
    typingWords: ['copy', 'move', 'paste', 'undo', 'rename', 'cut'], quiz: [question('After Copy + Paste, the original is…', ['Still where it was', 'Deleted', 'Renamed'], 0, 'Copy makes a twin. Nothing happens to the original.'), question('What does Cut + Paste do?', ['Moves the file', 'Makes two of it', 'Deletes it forever'], 0, 'Cut picks it up. Paste puts it down in the new spot.'), question('Which shortcut undoes your last action?', ['Ctrl + Z', 'Ctrl + U', 'Alt + Tab'], 0, 'Ctrl+Z works in File Explorer, Notepad, browsers, and later Excel.'), question('When should you copy instead of move?', ['When you want to keep the original too', 'Never', 'Only when a file is big'], 0, 'Copy is for when you need it in two places.'), question('What should you check before you paste?', ["That you're in the right folder", 'The clock', 'The volume'], 0, 'Pasting into the wrong folder is how files get "lost."'), question('You deleted something by accident. What do you do first?', ['Press Ctrl + Z right away, then tell a grown-up', 'Hide it', 'Keep going and hope'], 0, 'Undo works best right away, and a grown-up can check the Recycle Bin.')], passScore: 5,
    parentChecks: ['**Animals** and **Space** folders are inside My Projects', 'Favorite Animal Facts was moved into Animals (not left in My Projects)', 'A copy in Space is renamed **Space Animal Facts**', 'Shows you Ctrl+Z undoing a rename'], chest: [question('Cut + Paste = …', ['move', 'copy', 'delete'], 0, null), question('Undo = …', ['Ctrl + Z', 'Ctrl + S', 'Alt + Tab'], 0, null), question('Rename shortcut?', ['F2', 'F5', 'Esc'], 0, null)], item: 'undo-amulet', practice: 'Copy a file into 2 different folders, rename each copy, then undo one rename with Ctrl+Z.', parentWatch: 'If a Ctrl+Z ever asks "Are you sure you want to delete…?", he should click **No** and call you.', after: null,
  },
  {
    id: 's4', track: standard, number: 4, title: 'Shortcut Power + Home Row', minutes: '~35-40', newIdea: 'Ctrl shortcuts for text, selecting text, typing posture',
    warmup: [question('Undo =', ['Ctrl + Z', 'Ctrl + U'], 0, null), question('Copy vs move: which keeps the original?', ['copy', 'move'], 0, null), question('Cut + Paste =', ['move', 'copy'], 0, null)],
    learn: [card('A **shortcut** = hold a helper key (**Ctrl**) + tap a letter.'), card('**Ctrl + C** copy · **Ctrl + X** cut · **Ctrl + V** paste · **Ctrl + Z** undo · **Ctrl + S** save · **Ctrl + A** select all.'), card('They work in lots of apps: Notepad, File Explorer, browsers, and later Excel.'), card('**Select text** by click-and-dragging, or hold **Shift** + press the arrow keys.'), card('**Home row:** left fingers rest on **A S D F**, right fingers on **J K L ;**. **F** and **J** have little bumps so you can find them without looking.'), card('**Posture:** sit back, feet flat, wrists floating (not slumped on the desk), eyes on the screen.'), card('**Accuracy first.** Speed comes later on its own.')],
    mission: [step('Open **Favorite Animal Facts** (Documents → [your folder] → My Projects → Animals).'), step('Put your fingers on the home row. Feel the bumps on F and J. Click at the very end of your text and type one new sentence.'), step('**Select** your first sentence: click right before it, hold **Shift**, press **→** until the whole sentence is highlighted. (Dragging with the mouse works too.)'), step('Press **Ctrl + C** (copy). Click at the very end of your text. Press **Enter**, then **Ctrl + V** (paste). Your sentence is there twice!'), step('Press **Ctrl + Z**. The pasted copy disappears.'), step('Press **Ctrl + S** to save.'), step("Prove it: close Notepad, then reopen the file. Your new sentence is still there, so it saved! (Closing and reopening is the real test. Don't trust little marks on the screen.)"), step('**Typing game:** home-row drill (in CodeQuest once the typing game exists).')],
    typingWords: ['ask', 'dad', 'sad', 'fall', 'flask', 'glad', 'half', 'hall', 'shall', 'lads'], quiz: [question('What does Ctrl + S do?', ['Saves', 'Selects all', 'Shuts down'], 0, 'S for Save. Use it a lot.'), question('What does Ctrl + V do?', ['Pastes', 'Opens videos', 'Undoes'], 0, 'V sits right next to C, so copy and paste are side by side.'), question('Ctrl + X, then Ctrl + V does…', ['A move', 'A copy', 'A delete'], 0, 'X cuts it out, V puts it down somewhere new.'), question('Which fingers go on the bumps?', ['Left pointer finger on F, right pointer finger on J', 'Thumbs on Space', 'Pinkies on A and ;'], 0, 'The bumps let your fingers find home without looking.'), question("When you're learning to type, what matters most first?", ['Accuracy', 'Speed', 'Pressing hard'], 0, 'Fingers learn what you practice. Practice it right, and speed follows.'), question('What does holding Shift and pressing → do in Notepad?', ['Selects text one letter at a time', 'Deletes a line', 'Closes Notepad'], 0, 'Shift + arrows is how you highlight text without the mouse.')], passScore: 5,
    parentChecks: ['Selects a sentence (Shift + arrows, or dragging)', 'Copies and pastes with Ctrl+C / Ctrl+V', 'Undoes the paste with Ctrl+Z', 'Saves with Ctrl+S, closes, reopens, and the change is there', 'Shows you home-row position with pointer fingers on the F and J bumps'], chest: [question('Ctrl + C = …', ['copy', 'close', 'cut'], 0, null), question('Ctrl + A = …', ['select all', 'save as', 'alt'], 0, null), question('Bumps are on…', ['F and J', 'A and ;', 'G and H'], 0, null)], item: 'copy-crystal-staff', practice: 'Write 3 sentences, use Ctrl+X / Ctrl+V to put them in a different order, then Ctrl+S.', parentWatch: null, after: null,
  },
  {
    id: 's5', track: standard, number: 5, title: 'Search Smart, Stay Safe', minutes: '~35-40', newIdea: 'search results and ads, spotting tricks, private info, citing where facts come from',
    warmup: [question('Ctrl + S =', ['save', 'select'], 0, null), question('Ctrl + V =', ['paste', 'video'], 0, null), question('Accuracy or speed first?', ['accuracy', 'speed'], 0, null)],
    learn: [card('Browser parts: **address bar** (the web address) · **tabs** · **Back ←** · **Refresh ⟳**.'), card('A **search engine** finds pages. Some results at the top are **ads**, labeled **"Ad"** or **"Sponsored."** Someone paid to be there.'), card("The first result isn't always the best one. Pick sites you trust, like ones your grown-up approved or well-known education sites."), card('**Check the address.** Weird spellings like **micros0ft-help.com** (a zero instead of an o) are tricks.'), card('The lock or site-info icon by the address only means the connection is private. **It does not mean the site is honest.**'), card('**Private info:** full name, address, school, phone, passwords, photos of you, where you are right now.'), card('**Passwords are shared with parents only.** Not friends, not "game helpers."'), card('**Tricks use hurry words:** "Hurry!" "Last chance!" "Your computer is infected!"'), card('**The STOP rule: Stop. Don\'t click. Tell a grown-up.** Use it for downloads, installs, "you won," virus warnings, requests for info or passwords, making accounts, anything that costs money, messages from strangers, and anything scary or weird.')],
    mission: [step('**Spot It** (inside CodeQuest, pretend screens): 6 cards, pick **OK** or **STOP**:', { kind: 'spotIt', cards: [spot('A results page where the top 2 results say "Sponsored". Is it OK to pick the first result that isn\'t an ad?', 'ok'), spot('"micros0ft-help.com: Your PC is infected! Call now!"', 'stop'), spot('"FREE game coins! Just enter your game password"', 'stop'), spot("A popular encyclopedia page your grown-up bookmarked", 'ok'), spot('"Make an account to keep reading (enter your birthday)"', 'stop'), spot('Game chat from a stranger: "add me on another app, I\'ll give u free skins"', 'stop')], pass: 5 }), step('open a new tab (the **+** next to your tabs). Search: **how fast can a cheetah run**', { grownup: true }), step('Find any results labeled **Ad** or **Sponsored**. Point them out to your grown-up. Don\'t click them.'), step('Pick a result from a site you trust (your grown-up says OK). Find the answer.'), step("Tell your grown-up: the fact, the website's name, and why you trusted it."), step('Select the fact on the page and press **Ctrl + C**. Open Notepad, press **Ctrl + V**. On a new line type **Source:** and the website\'s name. **Save As** into **Documents → [your folder] → My Projects → Animals** with the name **Cheetah Fact**.'), step('Close **only your search tab**, using the small X on the tab.')],
    typingWords: ['search', 'source', 'private', 'sponsored', 'stop', 'trust'], quiz: [question('Is the first search result always the best answer?', ['No. It might be an ad, so check the site', 'Yes, always', 'Only on weekends'], 0, "Being first can be paid for. Being trustworthy can't."), question('A game says "Install this now for FREE!" You…', ['Stop and tell a grown-up', 'Install it', 'Install it, then tell'], 0, 'Installs can carry bad software. Grown-ups decide.'), question('Which one is private?', ['Your home address', 'Your favorite color', 'A made-up game nickname'], 0, 'An address tells a stranger where you are in real life.'), question('What does the lock or site-info icon by the address mean?', ["The connection is private. It doesn't prove the site is honest", 'The site is 100% safe', 'The site is for kids'], 0, 'Tricksters can have a private connection too.'), question('Someone in game chat asks what school you go to. You…', ["Don't answer, and tell a grown-up", 'Tell them', 'Ask them first'], 0, 'Your school is private, no matter how friendly they seem.'), question('What\'s wrong with "micros0ft-help.com"?', ['A zero instead of an "o". It\'s a lookalike trick', 'Nothing', 'It\'s a faster version'], 0, 'Tricksters copy real names with tiny changes.'), question('Why write down where a fact came from?', ['So you and others can check it', 'To make the file longer', 'No reason'], 0, 'A source lets anyone double-check the fact.')], passScore: 6,
    parentChecks: ['Gets at least 5 of 6 Spot It cards right (the app shows you his answers)', 'Searches and points out Ad/Sponsored results without clicking them', 'Picks a trustworthy site and tells you why', 'Saves **Cheetah Fact** with the fact + source in the Animals folder', 'Explains the STOP rule and gives you 2 examples'], chest: [question('"Sponsored" means…', ['someone paid to be there', "it's the best answer", "it's from your teacher"], 0, null), question('Passwords are shared with…', ['parents only', 'best friends', 'game helpers'], 0, null), question('"Hurry! Last chance!" on a pop-up is a…', ['warning sign of a trick', 'reason to hurry', 'prize'], 0, null)], item: 'scam-spotter-helmet', practice: 'With a grown-up nearby, search for one fact about a different animal, save it with its source as a new file in Animals, then do a new shuffled round of Spot It cards.', parentWatch: null, after: ['create, save, find, copy, move, rename, and reopen files', 'use Alt+Tab, snap, Ctrl+C/X/V/Z/S/A', 'sit and place his fingers for typing', 'search, skip ads, spot lookalike tricks, and cite where a fact came from', 'use the STOP rule'],
  },
];

LESSONS.forEach(deepFreeze);
deepFreeze(LESSONS);

export function getLesson(id) {
  for (let index = 0; index < LESSONS.length; index += 1) {
    if (LESSONS[index].id === id) return LESSONS[index];
  }
  return null;
}

export function trackLessons(track) {
  if (track !== guided && track !== standard) return [];
  return LESSONS.filter((lesson) => lesson.track === track);
}
