// Builds the two small synchronous indexes the Pro entry needs so it never has to load a question bank or the labs
// content just to summarize progress:
//   src/pro/exam/index-data.js       per exam: question ids in bank order + which are held out (checkOnly)
//   src/pro/ui/labs/catalog-index.js per lab: id, icon, name, pass mark, case ids (what labSummary reads), and the
//                                    objectives it practices per exam (objs = Security+, examObjs = the others)
// Run after any bank or lab content change:  node src/pro/exam/tools/build-index.mjs
// Check only (exit 1 if stale, writes nothing):  node src/pro/exam/tools/build-index.mjs --check
// test/pro-exams.test.js fails when either file differs from what this script would write.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const here = (p) => fileURLToPath(new URL(p, import.meta.url));
export const EXAM_INDEX_PATH = here('../index-data.js');
export const LAB_INDEX_PATH = here('../../ui/labs/catalog-index.js');

export async function examIndexSource() {
  const { BLUEPRINTS } = await import('../blueprints.js');
  const { BANK_LOADERS } = await import('../loaders.js');
  const lines = [];
  for (const bp of BLUEPRINTS) {
    const exam = await BANK_LOADERS[bp.id]();
    const ids = exam.questions.map((q) => q.id);
    const held = exam.questions.map((q, i) => (q.checkOnly ? i : -1)).filter((i) => i >= 0);
    lines.push(`  ${JSON.stringify(bp.id)}: { ids: ${JSON.stringify(ids)}, held: ${JSON.stringify(held)} },`);
  }
  return `// GENERATED by src/pro/exam/tools/build-index.mjs from the question banks. Do not edit; rerun the script.
// Per exam: every question id in bank order, and the positions of held-out (checkOnly) questions.
export default {
${lines.join('\n')}
};
`;
}

export async function labIndexSource() {
  const { LABS } = await import('../../labs/catalog.js');
  const labs = LABS.map((l) => `  ${JSON.stringify({ id: l.id, icon: l.icon, name: l.name, pass: l.pass, objs: l.objs, examObjs: l.examObjs, cases: l.cases.map((c) => ({ id: c.id })) })},`);
  return `// GENERATED by src/pro/exam/tools/build-index.mjs from src/pro/labs/catalog.js. Do not edit; rerun the script.
// What labSummary and the exam pages need (cases, pass marks, objectives per exam), without loading the labs content.
export default [
${labs.join('\n')}
];
`;
}

const read = (p) => { try { return readFileSync(p, 'utf8'); } catch { return null; } };

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const check = process.argv.includes('--check');
  let stale = 0;
  for (const [path, build] of [[EXAM_INDEX_PATH, examIndexSource], [LAB_INDEX_PATH, labIndexSource]]) {
    const next = await build();
    if (read(path) === next) { console.log(`up to date: ${path}`); continue; }
    stale += 1;
    if (check) console.log(`STALE: ${path}`);
    else { writeFileSync(path, next); console.log(`wrote ${path}`); }
  }
  if (check && stale) process.exit(1);
}
